name: Metrics
on:
  schedule: 
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: yuvan0309
          template: classic
          base: repositories
          config_display: columns
          config_timezone: Asia/Kolkata
          config_order: activity, community, repositories, metadata
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_visibility: public
          plugin_activity_limit: 5
          plugin_activity_timestamps: yes
          plugin_contributors: yes
          plugin_contributors_sections: commits, pull-requests, reviews, issues
          plugin_contributors_order: desc
          plugin_contributors_limit: 5
