name: Update GitHub Activity Graph

on:
  schedule:
    - cron: "0 * * * *"  # Runs every hour
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-graph:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: pip install requests matplotlib numpy

      - name: Run Python Script
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: python generate_graph.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add github_activity.png
          git commit -m "Updated GitHub activity graph" || echo "No changes to commit"
          git push
